#!/usr/bin/env bash

set -e

APP_NAME="bringup"
# ---- Configuration ----
DOMAIN="bringup.localhost"
MKCERT_VERSION="v1.4.4"
COMPOSE_COMMIT="main"

# ---- Colors ----
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 0. Ensure sudo/root
if [ "$EUID" -ne 0 ]; then
  error "Please run as root or with sudo"
  exit 1
fi

USER_NAME=${SUDO_USER:-$(whoami)}
OS="$(uname -s)"
USER_HOME=$(eval echo "~$USER_NAME")

# On Mac, /opt is not shared with Docker by default.
# If we are already in the repo, use current dir. Otherwise use home.
if [ "$OS" = "Darwin" ]; then
  if [ -f "docker-compose.yml" ]; then
    INSTALL_DIR="$(pwd)"
  else
    INSTALL_DIR="$USER_HOME/.bringup"
  fi
else
  INSTALL_DIR="/opt/bringup"
fi

COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
CERT_DIR="$INSTALL_DIR/certs"

log "User: $USER_NAME"
log "OS: $OS"
log "Install Dir: $INSTALL_DIR"

# ----------------------------
# Docker Setup
# ----------------------------

install_docker_linux() {
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  usermod -aG docker "$USER_NAME"
}

check_docker() {
  if command -v docker >/dev/null 2>&1; then
    log "Docker already installed"
    return
  fi

  case "$OS" in
    Linux)
      install_docker_linux
      ;;
    Darwin)
      error "Install Docker Desktop for Mac"
      exit 1
      ;;
    *)
      error "Unsupported OS"
      exit 1
      ;;
  esac
}

check_docker

if ! docker info >/dev/null 2>&1; then
  error "Docker not running"
  exit 1
fi

# ----------------------------
# mkcert Setup
# ----------------------------

install_mkcert() {
  log "Installing mkcert..."

  case "$OS" in
    Linux)
      apt-get update -y || true
      apt-get install -y libnss3-tools curl || true

      TMP_FILE="/tmp/mkcert"
      URL="https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64"

      curl -fsSL "$URL" -o "$TMP_FILE"

      chmod +x "$TMP_FILE"
      mv "$TMP_FILE" /usr/local/bin/mkcert
      ;;
    Darwin)
      brew install mkcert nss
      ;;
    *)
      error "Install mkcert manually for this OS"
      exit 1
      ;;
  esac
}

if ! command -v mkcert >/dev/null 2>&1; then
  install_mkcert
fi

log "Setting up mkcert CA..."
# Identify the regular user's CA Root to ensure consistency across root and user calls.
export CAROOT=$(sudo -u "$USER_NAME" mkcert -CAROOT 2>/dev/null || echo "$USER_HOME/.local/share/mkcert")
mkdir -p "$CAROOT"
chown -R "$USER_NAME:$USER_NAME" "$CAROOT" 2>/dev/null || true

# 1. Update system trust store (as root)
mkcert -install

# 2. Update browser trust stores (as regular user)
# This resolves the "no Firefox/Chrome security databases found" error when running as root.
if [ "$EUID" -eq 0 ] && [ "$USER_NAME" != "root" ]; then
    log "Updating browser trust stores for $USER_NAME..."
    sudo -u "$USER_NAME" CAROOT="$CAROOT" mkcert -install || true
fi

# ----------------------------
# Prepare directories
# ----------------------------

mkdir -p "$INSTALL_DIR"
mkdir -p "$CERT_DIR"

# ----------------------------
# Copy or Download docker compose
# ----------------------------

if [ -f "docker-compose.yml" ]; then
  # Only copy if source and destination are different
  if [ "$(realpath docker-compose.yml)" != "$(realpath "$COMPOSE_FILE")" ]; then
    log "Using local docker-compose.yml"
    cp "docker-compose.yml" "$COMPOSE_FILE"
  else
    log "Using docker-compose.yml in current directory"
  fi
else
  log "Downloading docker compose..."
  COMPOSE_URL="https://raw.githubusercontent.com/bringup-labs/bringup-release/${COMPOSE_COMMIT}/docker-compose.yml"
  curl -fsSL "$COMPOSE_URL" -o "$COMPOSE_FILE"
fi

# ----------------------------
# Generate TLS cert
# ----------------------------

log "Generating TLS cert via mkcert..."

mkcert -key-file "$CERT_DIR/key.pem" \
       -cert-file "$CERT_DIR/cert.pem" \
       "*.${DOMAIN}" \
       "${DOMAIN}" \
       "localhost" \
       "127.0.0.1" \
       "::1"

# Copy mkcert root CA so containers (e.g. Next.js) can trust it
cp "$CAROOT/rootCA.pem" "$CERT_DIR/rootCA.pem"

# Generate Traefik TLS config alongside certs
log "Generating tls.yml..."
cat > "$CERT_DIR/tls.yml" <<'EOF'
tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem
EOF


# ----------------------------
# Generate .env for docker-compose
# ----------------------------

log "Generating .env file..."
cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DOMAIN=${DOMAIN}
CERT_DIR=${CERT_DIR}
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_BUCKET=bagmaster-storage
KC_ADMIN_USER=admin
KC_ADMIN_PASSWORD=password
KC_CLIENT_SECRET=next-auth-secret-change-in-production
JENKINS_ADMIN_USER=admin
JENKINS_ADMIN_PASSWORD=admin12345
JENKINS_WEBHOOK_TOKEN=randomtoken
EOF

# ----------------------------
# Hosts entry
# ----------------------------

SUBDOMAINS="app idp api s3 pipeline visualizer"
for sub in $SUBDOMAINS; do
  FQDN="${sub}.${DOMAIN}"
  if ! grep -qE "127.0.0.1\s+${FQDN}" /etc/hosts; then
    log "Adding $FQDN to /etc/hosts"
    echo "127.0.0.1 $FQDN" >> /etc/hosts
  fi
done

# ----------------------------
# Pull images
# ----------------------------

log "Pulling images..."
sudo -u "$USER_NAME" docker compose -f "$COMPOSE_FILE" pull

# ----------------------------
# Start services
# ----------------------------

log "Cleaning up existing containers..."
sudo -u "$USER_NAME" docker compose -f "$COMPOSE_FILE" down --remove-orphans || true

log "Starting services..."
sudo -u "$USER_NAME" docker compose -f "$COMPOSE_FILE" up -d

# ----------------------------
# Wait for readiness
# ----------------------------

log "Waiting for app..."

MAX_RETRIES=40
RETRY=0

for ((i=1;i<=MAX_RETRIES;i++)); do
  if sudo -u "$USER_NAME" curl -sk "https://$DOMAIN" >/dev/null; then
    log "App is ready!"
    break
  fi

  sleep 2

  if [ "$i" -eq "$MAX_RETRIES" ]; then
    error "App failed to start"
  fi
done

# ----------------------------
# Done
# ----------------------------

log "Installation complete 🎉"

echo "👉 Open: https://app.$DOMAIN"
echo ""
echo "🔑 Login Credentials:"
echo "   User: demo"
echo "   Pass: demo"
echo ""
echo "⚠️ Re-login may be required for Docker group changes"
